### ISSUE TITLE
Question about the use of the files

### ISSUE THREAD

**Issue by Nastras** [3dprintpt/K1_organized_firmware#1]
Hey thanks a lot for your work. I have a question about using your files. Where do I copy the files exactly. In Klipper browser menu to config and delete all old files there?

You write that you should make the changes in USER OVERRIDES. Where should that be exactly?

Greetings

**Comment by 3dprintpt** [comment]
Hello.

You just need to replace printer.cfg, create the folder K1 and place all
the other files inside.

For the overrides, of you want to change anything included on the “include”
files inside the K1 folder, paste the what you need on the bottom of
printer.cfg
There is a section where I described where to do it.
This pasted lines will override what is on the other files.

Nastra ***@***.***> escreveu em sáb., 2/09/2023 às 18:18 :

**Comment by Nastras** [comment]
Ahhh now I get it. I will try it tomorrow.
Thanks for your quick reply.

**Comment by Nastras** [comment]
I need to open the issue again. I am in the process of customizing my config. For this I want to change my esters from the stepper. When I insert the value in the given area and save and restart it does not take it into the included file in the K1 folder. I think I am doing something wrong here.

Would be happy if you can help me again?

Thank you!

<img width="1404" alt="Bildschirmfoto 2023-09-03 um 17 27 52" src="https://github.com/3dprintpt/K1_organized_firmware/assets/27686185/73d199ff-5b2a-4afa-80a2-1f6d5fdbb7eb">

**Comment by 3dprintpt** [comment]
It should be working.
What you did is the correct way…
Can you check measurements again, please?


Nastra ***@***.***> escreveu em dom., 3/09/2023 às 16:31 :

**Comment by Nastras** [comment]
Another question. Why is it not allowed to edit the files in the K1 folder directly?

**Comment by Nastras** [comment]
I have now saved the printer.cfg again and made a restart but nothing changes in the stepper.cfg.

![Uploading Bildschirmfoto 2023-09-03 um 17.38.03.png…]()

**Comment by Nastras** [comment]
Should the value be automatically removed from the User Overrides area after saving?

[extruder]
rotation_distance: 6.486

**Comment by Nastras** [comment]
I have now spent several hours setting up my printer. I really wanted to use your files. But as soon as I replace them with the ones from the root image, I get an error when I start printing. There are still errors.  I give up no more desire. 
<img width="672" alt="Bildschirmfoto 2023-09-04 um 12 12 40" src="https://github.com/3dprintpt/K1_organized_firmware/assets/27686185/aa5f0483-e078-4be3-80e3-86d9a86b7e9d">

**Comment by 3dprintpt** [comment]
What version of the rooted firmware are you using?
Looks an older one…
I’m on 5.3.1.28 and using this files.

Nastra ***@***.***> escreveu em seg., 4/09/2023 às 11:15 :

**Comment by Nastras** [comment]
Now i also use 5.3.1.28

After much tinkering the setup now works and it is not because of your files😅. Sorry.
What still does not work is the user overrides area. I have now removed this and change my stuff directly in the files.

Maybe you can explain me briefly why you have installed this area at all, what advantages should bring this?

I could not fix the problem with the start print macro. I think it is a problem with the gcode in the slicer profile of S3D. Maybe you have an idea what has to be different in the gcode to call the start print macro correctly?

I have as a fix removed the start print macro from the gcode completely and created my own gcode.

One more question about the fan assignments. I tried it myself yesterday in the config but it didn't really work because I don't know how to do it. Is there from you still an improved file?

**Comment by Nastras** [comment]
![IMG_4858](https://github.com/3dprintpt/K1_organized_firmware/assets/27686185/e2da6d69-b5b7-4eeb-a389-1a99850c799d)

**Comment by 3dprintpt** [comment]
Hello Nastras

There was a problem in the files with the START_PRINT macro. I uploaded new files yesterday. It was missing some data.

About the user overrides, once you add any info (like you did with rotation distance) just save and restart.
It remains there. The use of this section is to avoid messing too much with the files on the folder.
Since I included the files at the beginning of printer.cfg, everything set at the bottom is loaded after the values set in the included files and remains the updated info.
This is why it is called override. Not sure If I'm clear, anything I can help let me know...
About changing the files in the folder, it is possible. I just wanted to avoid messing too much.
Your start_code on simplify is correct.
Check if you have the latest files from yesterday.

**Comment by Nastras** [comment]
Hi thank you very much for the information. I am reassured that the error was not with me. I will try it out later.

Regarding the fan, I actually meant the correct designation in the fluid surface. There it says only Fan 1, Fan 2.....

Would it not be possible that the correct names are displayed there the fan?

**Comment by Nastras** [comment]
Where can I find the current files? In the Github repo is the last change three days ago?

**Comment by 3dprintpt** [comment]
I’m working on the fans naming and on using the complete print area. As
soon as I have something, I will share.
There are lots of places it need to be changed because of the variables
function.

Nastra ***@***.***> escreveu em ter., 5/09/2023 às 13:12 :

**Comment by Nastras** [comment]
Ok that's cool .-)

Where can I find the current files? In the Github repo is the last change three days ago?

**Comment by Nastras** [comment]
Would be really cool if you could answer me briefly so I can use the start_print. So far I have to set everything via the code in the slicer.
Where can I find the current files? In the Github repo is the last change three days ago?

**Comment by Nastras** [comment]
I have now created a simplified config for myself. I was really hoping to use yours and follow your repo in the future but if the package is buggy it doesn't do me any good. Very sad.

**Comment by 3dprintpt** [comment]
I’m glad you solved it.
There is nothing buggy in it, plenty of other using it, including myself.
Maybe you missed the update…

Nastra ***@***.***> escreveu em dom., 10/09/2023 às 09:23 :

**Comment by Nastras** [comment]
> There was a problem in the files with the START_PRINT macro. I uploaded new files yesterday. It was missing som

Here you said something else?

**Comment by 3dprintpt** [comment]
No. Only that.
But as I said, START_PRINT has been corrected.
If something is not working, perhaos your start code is not correct.

Nastra ***@***.***> escreveu em dom., 10/09/2023 às 09:28 :
